### PR TITLE
Port to scala 3

### PR DESCRIPTION
**Pull request by cquiroz**

### CODE REVIEW

**Comment by tpolecat** [comment]
@cquiroz what's the status of this? Is it cross-publishing to 2 and 3?

**Comment by cquiroz** [comment]
It is not, though now looking at the changes perhaps it is possible except for a couple of test. Maybe we can try to do so

**Comment by cquiroz** [comment]
@tpolecat I guess this could be merged?

**Comment by tpolecat** [comment]
I think we can merge this once conflicts are resolved. Probably just update all deps.

**Comment by cquiroz** [comment]
Ready to be merged

**Pull request merged**
